// This file is part of arduino-flasher-cli.
//
// Copyright 2025 ARDUINO SA (http://www.arduino.cc/)
//
// This software is released under the GNU General Public License version 3,
// which covers the main part of arduino-flasher-cli.
// The terms of this license can be found at:
// https://www.gnu.org/licenses/gpl-3.0.en.html
//
// You can be released from the requirements of the above licenses by purchasing
// a commercial license. Buying such a license is mandatory if you want to
// modify or otherwise use the software for commercial activities involving the
// Arduino software without disclosing the source code of your own applications.
// To purchase a commercial license, send an email to license@arduino.cc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cc/arduino/flasher/v1/common.proto

package flasher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*DownloadProgress_Start
	//	*DownloadProgress_Update
	//	*DownloadProgress_End
	Message isDownloadProgress_Message `protobuf_oneof:"message"`
}

func (x *DownloadProgress) Reset() {
	*x = DownloadProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgress) ProtoMessage() {}

func (x *DownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgress.ProtoReflect.Descriptor instead.
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_common_proto_rawDescGZIP(), []int{0}
}

func (m *DownloadProgress) GetMessage() isDownloadProgress_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *DownloadProgress) GetStart() *DownloadProgressStart {
	if x, ok := x.GetMessage().(*DownloadProgress_Start); ok {
		return x.Start
	}
	return nil
}

func (x *DownloadProgress) GetUpdate() *DownloadProgressUpdate {
	if x, ok := x.GetMessage().(*DownloadProgress_Update); ok {
		return x.Update
	}
	return nil
}

func (x *DownloadProgress) GetEnd() *DownloadProgressEnd {
	if x, ok := x.GetMessage().(*DownloadProgress_End); ok {
		return x.End
	}
	return nil
}

type isDownloadProgress_Message interface {
	isDownloadProgress_Message()
}

type DownloadProgress_Start struct {
	// Sent when a download is started.
	Start *DownloadProgressStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type DownloadProgress_Update struct {
	// Progress updates for a download.
	Update *DownloadProgressUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type DownloadProgress_End struct {
	// Sent when a download is finished or failed.
	End *DownloadProgressEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*DownloadProgress_Start) isDownloadProgress_Message() {}

func (*DownloadProgress_Update) isDownloadProgress_Message() {}

func (*DownloadProgress_End) isDownloadProgress_Message() {}

type DownloadProgressStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// URL of the download.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// The label to display on the progress bar.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *DownloadProgressStart) Reset() {
	*x = DownloadProgressStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadProgressStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgressStart) ProtoMessage() {}

func (x *DownloadProgressStart) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgressStart.ProtoReflect.Descriptor instead.
func (*DownloadProgressStart) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadProgressStart) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadProgressStart) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DownloadProgressUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Size of the downloaded portion of the file.
	Downloaded int64 `protobuf:"varint,1,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	// Total size of the file being downloaded.
	TotalSize int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
}

func (x *DownloadProgressUpdate) Reset() {
	*x = DownloadProgressUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgressUpdate) ProtoMessage() {}

func (x *DownloadProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgressUpdate.ProtoReflect.Descriptor instead.
func (*DownloadProgressUpdate) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadProgressUpdate) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *DownloadProgressUpdate) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DownloadProgressEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// True if the download is successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Info or error message, depending on the value of 'success'. Some examples:
	// "File xxx already downloaded" or "Connection timeout".
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DownloadProgressEnd) Reset() {
	*x = DownloadProgressEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadProgressEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgressEnd) ProtoMessage() {}

func (x *DownloadProgressEnd) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgressEnd.ProtoReflect.Descriptor instead.
func (*DownloadProgressEnd) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadProgressEnd) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadProgressEnd) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cc_arduino_flasher_v1_common_proto protoreflect.FileDescriptor

var file_cc_arduino_flasher_v1_common_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0xec, 0x01, 0x0a, 0x10,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x44, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x47, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75,
	0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x3e, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63,
	0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x15, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x57, 0x0a, 0x16, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x49, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2d, 0x66, 0x6c,
	0x61, 0x73, 0x68, 0x65, 0x72, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63,
	0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x3b, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cc_arduino_flasher_v1_common_proto_rawDescOnce sync.Once
	file_cc_arduino_flasher_v1_common_proto_rawDescData = file_cc_arduino_flasher_v1_common_proto_rawDesc
)

func file_cc_arduino_flasher_v1_common_proto_rawDescGZIP() []byte {
	file_cc_arduino_flasher_v1_common_proto_rawDescOnce.Do(func() {
		file_cc_arduino_flasher_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_cc_arduino_flasher_v1_common_proto_rawDescData)
	})
	return file_cc_arduino_flasher_v1_common_proto_rawDescData
}

var file_cc_arduino_flasher_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cc_arduino_flasher_v1_common_proto_goTypes = []any{
	(*DownloadProgress)(nil),       // 0: cc.arduino.flasher.v1.DownloadProgress
	(*DownloadProgressStart)(nil),  // 1: cc.arduino.flasher.v1.DownloadProgressStart
	(*DownloadProgressUpdate)(nil), // 2: cc.arduino.flasher.v1.DownloadProgressUpdate
	(*DownloadProgressEnd)(nil),    // 3: cc.arduino.flasher.v1.DownloadProgressEnd
}
var file_cc_arduino_flasher_v1_common_proto_depIdxs = []int32{
	1, // 0: cc.arduino.flasher.v1.DownloadProgress.start:type_name -> cc.arduino.flasher.v1.DownloadProgressStart
	2, // 1: cc.arduino.flasher.v1.DownloadProgress.update:type_name -> cc.arduino.flasher.v1.DownloadProgressUpdate
	3, // 2: cc.arduino.flasher.v1.DownloadProgress.end:type_name -> cc.arduino.flasher.v1.DownloadProgressEnd
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cc_arduino_flasher_v1_common_proto_init() }
func file_cc_arduino_flasher_v1_common_proto_init() {
	if File_cc_arduino_flasher_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cc_arduino_flasher_v1_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadProgressStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadProgressUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_common_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadProgressEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cc_arduino_flasher_v1_common_proto_msgTypes[0].OneofWrappers = []any{
		(*DownloadProgress_Start)(nil),
		(*DownloadProgress_Update)(nil),
		(*DownloadProgress_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_flasher_v1_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cc_arduino_flasher_v1_common_proto_goTypes,
		DependencyIndexes: file_cc_arduino_flasher_v1_common_proto_depIdxs,
		MessageInfos:      file_cc_arduino_flasher_v1_common_proto_msgTypes,
	}.Build()
	File_cc_arduino_flasher_v1_common_proto = out.File
	file_cc_arduino_flasher_v1_common_proto_rawDesc = nil
	file_cc_arduino_flasher_v1_common_proto_goTypes = nil
	file_cc_arduino_flasher_v1_common_proto_depIdxs = nil
}
