// This file is part of arduino-flasher-cli.
//
// SPDX-FileCopyrightText: Arduino s.r.l. and/or its affiliated companies
// SPDX-License-Identifier: GPL-3.0-or-later

syntax = "proto3";

package cc.arduino.flasher.v1;

import "cc/arduino/flasher/v1/common.proto";

option go_package = "github.com/arduino/arduino-flasher-cli/rpc/cc/arduino/flasher/v1;flasher";

// Provides RPCs to flash Arduino images onto selected boards.
service Flasher {
  // Retrieves the images available for flashing
  rpc List(ListRequest) returns (ListResponse) {}

  // Starts the flashing process
  rpc Flash(FlashRequest) returns (stream FlashResponse);

  // Returns the available space for a given filesystem path
  // located on the arduino-flasher-cli storage device.
  rpc GetAvailableFreeSpace(GetAvailableFreeSpaceRequest) returns (GetAvailableFreeSpaceResponse) {}
}

// The type of the board that needs to be flashed.
enum Board {
  // Default, unspecified board type.
  BOARD_UNSPECIFIED = 0;
  // "UNO Q" board.
  BOARD_UNO_Q = 1;
  // "VENTUNO Q" board.
  BOARD_VENTUNO_Q = 2;
}

// The OS distribution to be flashed on the board.
enum OS {
  // Default, unspecified OS distribution.
  OS_UNSPECIFIED = 0;
  // "debian" distribution.
  OS_DEBIAN = 1;
  // "ubuntu" distribution.
  OS_UBUNTU = 2;
}

message ListRequest {
  // The type of the board that needs to be flashed.
  Board board = 1;
  // The OS distribution to be flashed on the board.
  OS os = 2;
}

message ListResponse {
  repeated Release releases = 1;
}

message Release {
  string build_id = 1;
  bool latest = 2;
}

message FlashRequest {
  // The version of the Debian image to download.
  string version = 1;
  // The path in which the image will be downloaded and extracted.
  // If an image file is already present, it will not be downloaded again.
  string temp_path = 2;
  // Preserve user partition if possible.
  bool preserve_user = 3;
  // Serial number of the target board to flash, as a decimal integer string.
  // Leave empty to target the first discovered board.
  string serial = 4;
  // The type of the board that needs to be flashed.
  Board board = 5;
  // The OS distribution to be flashed on the board.
  OS os = 6;
}

message FlashResponse {
  message Result {
    // Empty message, reserved for future expansion.
  }
  oneof message {
    // Progress of the download.
    DownloadProgress download_progress = 1;
    // Progress of the extraction.
    TaskProgress extraction_progress = 2;
    // Progress of qdl flashing.
    TaskProgress flash_progress = 3;
    // Flashing result.
    Result result = 4;
  }
}

message GetAvailableFreeSpaceRequest {
  // Filesystem path to be checked.
  string path = 1;
}

message GetAvailableFreeSpaceResponse {
  // Free space in bytes
  uint64 free_space = 1;
}
