// This file is part of arduino-flasher-cli.
//
// SPDX-FileCopyrightText: Arduino s.r.l. and/or its affiliated companies
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cc/arduino/flasher/v1/commands.proto

package flasher

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of the board that needs to be flashed.
type Board int32

const (
	// Default, unspecified board type.
	Board_BOARD_UNSPECIFIED Board = 0
	// "UNO Q" board.
	Board_BOARD_UNO_Q Board = 1
	// "VENTUNO Q" board.
	Board_BOARD_VENTUNO_Q Board = 2
)

// Enum value maps for Board.
var (
	Board_name = map[int32]string{
		0: "BOARD_UNSPECIFIED",
		1: "BOARD_UNO_Q",
		2: "BOARD_VENTUNO_Q",
	}
	Board_value = map[string]int32{
		"BOARD_UNSPECIFIED": 0,
		"BOARD_UNO_Q":       1,
		"BOARD_VENTUNO_Q":   2,
	}
)

func (x Board) Enum() *Board {
	p := new(Board)
	*p = x
	return p
}

func (x Board) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Board) Descriptor() protoreflect.EnumDescriptor {
	return file_cc_arduino_flasher_v1_commands_proto_enumTypes[0].Descriptor()
}

func (Board) Type() protoreflect.EnumType {
	return &file_cc_arduino_flasher_v1_commands_proto_enumTypes[0]
}

func (x Board) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Board.Descriptor instead.
func (Board) EnumDescriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{0}
}

// The OS distribution to be flashed on the board.
type OS int32

const (
	// Default, unspecified OS distribution.
	OS_OS_UNSPECIFIED OS = 0
	// "debian" distribution.
	OS_OS_DEBIAN OS = 1
	// "ubuntu" distribution.
	OS_OS_UBUNTU OS = 2
)

// Enum value maps for OS.
var (
	OS_name = map[int32]string{
		0: "OS_UNSPECIFIED",
		1: "OS_DEBIAN",
		2: "OS_UBUNTU",
	}
	OS_value = map[string]int32{
		"OS_UNSPECIFIED": 0,
		"OS_DEBIAN":      1,
		"OS_UBUNTU":      2,
	}
)

func (x OS) Enum() *OS {
	p := new(OS)
	*p = x
	return p
}

func (x OS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OS) Descriptor() protoreflect.EnumDescriptor {
	return file_cc_arduino_flasher_v1_commands_proto_enumTypes[1].Descriptor()
}

func (OS) Type() protoreflect.EnumType {
	return &file_cc_arduino_flasher_v1_commands_proto_enumTypes[1]
}

func (x OS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OS.Descriptor instead.
func (OS) EnumDescriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{1}
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of the board that needs to be flashed.
	Board Board `protobuf:"varint,1,opt,name=board,proto3,enum=cc.arduino.flasher.v1.Board" json:"board,omitempty"`
	// The OS distribution to be flashed on the board.
	Os OS `protobuf:"varint,2,opt,name=os,proto3,enum=cc.arduino.flasher.v1.OS" json:"os,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetBoard() Board {
	if x != nil {
		return x.Board
	}
	return Board_BOARD_UNSPECIFIED
}

func (x *ListRequest) GetOs() OS {
	if x != nil {
		return x.Os
	}
	return OS_OS_UNSPECIFIED
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Releases []*Release `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetReleases() []*Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

type Release struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Latest  bool   `protobuf:"varint,2,opt,name=latest,proto3" json:"latest,omitempty"`
}

func (x *Release) Reset() {
	*x = Release{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *Release) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *Release) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

type FlashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The version of the Debian image to download.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The path in which the image will be downloaded and extracted.
	// If an image file is already present, it will not be downloaded again.
	TempPath string `protobuf:"bytes,2,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	// Preserve user partition if possible.
	PreserveUser bool `protobuf:"varint,3,opt,name=preserve_user,json=preserveUser,proto3" json:"preserve_user,omitempty"`
	// Serial number of the target board to flash, as a decimal integer string.
	// Leave empty to target the first discovered board.
	Serial string `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	// The type of the board that needs to be flashed.
	Board Board `protobuf:"varint,5,opt,name=board,proto3,enum=cc.arduino.flasher.v1.Board" json:"board,omitempty"`
	// The OS distribution to be flashed on the board.
	Os OS `protobuf:"varint,6,opt,name=os,proto3,enum=cc.arduino.flasher.v1.OS" json:"os,omitempty"`
}

func (x *FlashRequest) Reset() {
	*x = FlashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashRequest) ProtoMessage() {}

func (x *FlashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashRequest.ProtoReflect.Descriptor instead.
func (*FlashRequest) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *FlashRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FlashRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

func (x *FlashRequest) GetPreserveUser() bool {
	if x != nil {
		return x.PreserveUser
	}
	return false
}

func (x *FlashRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *FlashRequest) GetBoard() Board {
	if x != nil {
		return x.Board
	}
	return Board_BOARD_UNSPECIFIED
}

func (x *FlashRequest) GetOs() OS {
	if x != nil {
		return x.Os
	}
	return OS_OS_UNSPECIFIED
}

type FlashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*FlashResponse_DownloadProgress
	//	*FlashResponse_ExtractionProgress
	//	*FlashResponse_FlashProgress
	//	*FlashResponse_Result_
	Message isFlashResponse_Message `protobuf_oneof:"message"`
}

func (x *FlashResponse) Reset() {
	*x = FlashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashResponse) ProtoMessage() {}

func (x *FlashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashResponse.ProtoReflect.Descriptor instead.
func (*FlashResponse) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (m *FlashResponse) GetMessage() isFlashResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *FlashResponse) GetDownloadProgress() *DownloadProgress {
	if x, ok := x.GetMessage().(*FlashResponse_DownloadProgress); ok {
		return x.DownloadProgress
	}
	return nil
}

func (x *FlashResponse) GetExtractionProgress() *TaskProgress {
	if x, ok := x.GetMessage().(*FlashResponse_ExtractionProgress); ok {
		return x.ExtractionProgress
	}
	return nil
}

func (x *FlashResponse) GetFlashProgress() *TaskProgress {
	if x, ok := x.GetMessage().(*FlashResponse_FlashProgress); ok {
		return x.FlashProgress
	}
	return nil
}

func (x *FlashResponse) GetResult() *FlashResponse_Result {
	if x, ok := x.GetMessage().(*FlashResponse_Result_); ok {
		return x.Result
	}
	return nil
}

type isFlashResponse_Message interface {
	isFlashResponse_Message()
}

type FlashResponse_DownloadProgress struct {
	// Progress of the download.
	DownloadProgress *DownloadProgress `protobuf:"bytes,1,opt,name=download_progress,json=downloadProgress,proto3,oneof"`
}

type FlashResponse_ExtractionProgress struct {
	// Progress of the extraction.
	ExtractionProgress *TaskProgress `protobuf:"bytes,2,opt,name=extraction_progress,json=extractionProgress,proto3,oneof"`
}

type FlashResponse_FlashProgress struct {
	// Progress of qdl flashing.
	FlashProgress *TaskProgress `protobuf:"bytes,3,opt,name=flash_progress,json=flashProgress,proto3,oneof"`
}

type FlashResponse_Result_ struct {
	// Flashing result.
	Result *FlashResponse_Result `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*FlashResponse_DownloadProgress) isFlashResponse_Message() {}

func (*FlashResponse_ExtractionProgress) isFlashResponse_Message() {}

func (*FlashResponse_FlashProgress) isFlashResponse_Message() {}

func (*FlashResponse_Result_) isFlashResponse_Message() {}

type GetAvailableFreeSpaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filesystem path to be checked.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetAvailableFreeSpaceRequest) Reset() {
	*x = GetAvailableFreeSpaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableFreeSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableFreeSpaceRequest) ProtoMessage() {}

func (x *GetAvailableFreeSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableFreeSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableFreeSpaceRequest) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableFreeSpaceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetAvailableFreeSpaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Free space in bytes
	FreeSpace uint64 `protobuf:"varint,1,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`
}

func (x *GetAvailableFreeSpaceResponse) Reset() {
	*x = GetAvailableFreeSpaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableFreeSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableFreeSpaceResponse) ProtoMessage() {}

func (x *GetAvailableFreeSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableFreeSpaceResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableFreeSpaceResponse) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailableFreeSpaceResponse) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

type FlashResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlashResponse_Result) Reset() {
	*x = FlashResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashResponse_Result) ProtoMessage() {}

func (x *FlashResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_flasher_v1_commands_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashResponse_Result.ProtoReflect.Descriptor instead.
func (*FlashResponse_Result) Descriptor() ([]byte, []int) {
	return file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP(), []int{4, 0}
}

var File_cc_arduino_flasher_v1_commands_proto protoreflect.FileDescriptor

var file_cc_arduino_flasher_v1_commands_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x22, 0x63,
	0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6c, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c,
	0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x53, 0x52, 0x02, 0x6f, 0x73, 0x22,
	0x4a, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66,
	0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x07, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x22, 0xe1, 0x01, 0x0a, 0x0c, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x32,
	0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x12, 0x29, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x53, 0x52, 0x02, 0x6f, 0x73, 0x22, 0xe9, 0x02,
	0x0a, 0x0d, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x56, 0x0a, 0x11, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x10, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x56, 0x0a, 0x13, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e,
	0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x12, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x4c, 0x0a, 0x0e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64,
	0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0d,
	0x66, 0x6c, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x45, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0x08, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x72, 0x65, 0x65, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3e, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x72, 0x65,
	0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x66, 0x72, 0x65, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x2a, 0x44, 0x0a,
	0x05, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x5f, 0x55, 0x4e, 0x4f, 0x5f, 0x51, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x5f, 0x56, 0x45, 0x4e, 0x54, 0x55, 0x4e, 0x4f, 0x5f,
	0x51, 0x10, 0x02, 0x2a, 0x36, 0x0a, 0x02, 0x4f, 0x53, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x4f, 0x53, 0x5f, 0x44, 0x45, 0x42, 0x49, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x4f, 0x53, 0x5f, 0x55, 0x42, 0x55, 0x4e, 0x54, 0x55, 0x10, 0x02, 0x32, 0xb9, 0x02, 0x0a, 0x07,
	0x46, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x22, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x05, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x12, 0x23, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x84, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x46, 0x72, 0x65, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x33, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46,
	0x72, 0x65, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x34, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x46, 0x72, 0x65, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2d, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2d, 0x63, 0x6c,
	0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x6c, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cc_arduino_flasher_v1_commands_proto_rawDescOnce sync.Once
	file_cc_arduino_flasher_v1_commands_proto_rawDescData = file_cc_arduino_flasher_v1_commands_proto_rawDesc
)

func file_cc_arduino_flasher_v1_commands_proto_rawDescGZIP() []byte {
	file_cc_arduino_flasher_v1_commands_proto_rawDescOnce.Do(func() {
		file_cc_arduino_flasher_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_cc_arduino_flasher_v1_commands_proto_rawDescData)
	})
	return file_cc_arduino_flasher_v1_commands_proto_rawDescData
}

var file_cc_arduino_flasher_v1_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cc_arduino_flasher_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cc_arduino_flasher_v1_commands_proto_goTypes = []any{
	(Board)(0),                            // 0: cc.arduino.flasher.v1.Board
	(OS)(0),                               // 1: cc.arduino.flasher.v1.OS
	(*ListRequest)(nil),                   // 2: cc.arduino.flasher.v1.ListRequest
	(*ListResponse)(nil),                  // 3: cc.arduino.flasher.v1.ListResponse
	(*Release)(nil),                       // 4: cc.arduino.flasher.v1.Release
	(*FlashRequest)(nil),                  // 5: cc.arduino.flasher.v1.FlashRequest
	(*FlashResponse)(nil),                 // 6: cc.arduino.flasher.v1.FlashResponse
	(*GetAvailableFreeSpaceRequest)(nil),  // 7: cc.arduino.flasher.v1.GetAvailableFreeSpaceRequest
	(*GetAvailableFreeSpaceResponse)(nil), // 8: cc.arduino.flasher.v1.GetAvailableFreeSpaceResponse
	(*FlashResponse_Result)(nil),          // 9: cc.arduino.flasher.v1.FlashResponse.Result
	(*DownloadProgress)(nil),              // 10: cc.arduino.flasher.v1.DownloadProgress
	(*TaskProgress)(nil),                  // 11: cc.arduino.flasher.v1.TaskProgress
}
var file_cc_arduino_flasher_v1_commands_proto_depIdxs = []int32{
	0,  // 0: cc.arduino.flasher.v1.ListRequest.board:type_name -> cc.arduino.flasher.v1.Board
	1,  // 1: cc.arduino.flasher.v1.ListRequest.os:type_name -> cc.arduino.flasher.v1.OS
	4,  // 2: cc.arduino.flasher.v1.ListResponse.releases:type_name -> cc.arduino.flasher.v1.Release
	0,  // 3: cc.arduino.flasher.v1.FlashRequest.board:type_name -> cc.arduino.flasher.v1.Board
	1,  // 4: cc.arduino.flasher.v1.FlashRequest.os:type_name -> cc.arduino.flasher.v1.OS
	10, // 5: cc.arduino.flasher.v1.FlashResponse.download_progress:type_name -> cc.arduino.flasher.v1.DownloadProgress
	11, // 6: cc.arduino.flasher.v1.FlashResponse.extraction_progress:type_name -> cc.arduino.flasher.v1.TaskProgress
	11, // 7: cc.arduino.flasher.v1.FlashResponse.flash_progress:type_name -> cc.arduino.flasher.v1.TaskProgress
	9,  // 8: cc.arduino.flasher.v1.FlashResponse.result:type_name -> cc.arduino.flasher.v1.FlashResponse.Result
	2,  // 9: cc.arduino.flasher.v1.Flasher.List:input_type -> cc.arduino.flasher.v1.ListRequest
	5,  // 10: cc.arduino.flasher.v1.Flasher.Flash:input_type -> cc.arduino.flasher.v1.FlashRequest
	7,  // 11: cc.arduino.flasher.v1.Flasher.GetAvailableFreeSpace:input_type -> cc.arduino.flasher.v1.GetAvailableFreeSpaceRequest
	3,  // 12: cc.arduino.flasher.v1.Flasher.List:output_type -> cc.arduino.flasher.v1.ListResponse
	6,  // 13: cc.arduino.flasher.v1.Flasher.Flash:output_type -> cc.arduino.flasher.v1.FlashResponse
	8,  // 14: cc.arduino.flasher.v1.Flasher.GetAvailableFreeSpace:output_type -> cc.arduino.flasher.v1.GetAvailableFreeSpaceResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cc_arduino_flasher_v1_commands_proto_init() }
func file_cc_arduino_flasher_v1_commands_proto_init() {
	if File_cc_arduino_flasher_v1_commands_proto != nil {
		return
	}
	file_cc_arduino_flasher_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Release); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FlashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FlashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAvailableFreeSpaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAvailableFreeSpaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cc_arduino_flasher_v1_commands_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FlashResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cc_arduino_flasher_v1_commands_proto_msgTypes[4].OneofWrappers = []any{
		(*FlashResponse_DownloadProgress)(nil),
		(*FlashResponse_ExtractionProgress)(nil),
		(*FlashResponse_FlashProgress)(nil),
		(*FlashResponse_Result_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_flasher_v1_commands_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cc_arduino_flasher_v1_commands_proto_goTypes,
		DependencyIndexes: file_cc_arduino_flasher_v1_commands_proto_depIdxs,
		EnumInfos:         file_cc_arduino_flasher_v1_commands_proto_enumTypes,
		MessageInfos:      file_cc_arduino_flasher_v1_commands_proto_msgTypes,
	}.Build()
	File_cc_arduino_flasher_v1_commands_proto = out.File
	file_cc_arduino_flasher_v1_commands_proto_rawDesc = nil
	file_cc_arduino_flasher_v1_commands_proto_goTypes = nil
	file_cc_arduino_flasher_v1_commands_proto_depIdxs = nil
}
