// This file is part of arduino-flasher-cli.
//
// SPDX-FileCopyrightText: Arduino s.r.l. and/or its affiliated companies
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cc/arduino/flasher/v1/commands.proto

package flasher

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flasher_List_FullMethodName                  = "/cc.arduino.flasher.v1.Flasher/List"
	Flasher_Flash_FullMethodName                 = "/cc.arduino.flasher.v1.Flasher/Flash"
	Flasher_GetAvailableFreeSpace_FullMethodName = "/cc.arduino.flasher.v1.Flasher/GetAvailableFreeSpace"
)

// FlasherClient is the client API for Flasher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides RPCs to flash Arduino images onto selected boards.
type FlasherClient interface {
	// Retrieves the images available for flashing
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Starts the flashing process
	Flash(ctx context.Context, in *FlashRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlashResponse], error)
	// Returns the available space for a given filesystem path
	// located on the arduino-flasher-cli storage device.
	GetAvailableFreeSpace(ctx context.Context, in *GetAvailableFreeSpaceRequest, opts ...grpc.CallOption) (*GetAvailableFreeSpaceResponse, error)
}

type flasherClient struct {
	cc grpc.ClientConnInterface
}

func NewFlasherClient(cc grpc.ClientConnInterface) FlasherClient {
	return &flasherClient{cc}
}

func (c *flasherClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Flasher_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flasherClient) Flash(ctx context.Context, in *FlashRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlashResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Flasher_ServiceDesc.Streams[0], Flasher_Flash_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlashRequest, FlashResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Flasher_FlashClient = grpc.ServerStreamingClient[FlashResponse]

func (c *flasherClient) GetAvailableFreeSpace(ctx context.Context, in *GetAvailableFreeSpaceRequest, opts ...grpc.CallOption) (*GetAvailableFreeSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableFreeSpaceResponse)
	err := c.cc.Invoke(ctx, Flasher_GetAvailableFreeSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlasherServer is the server API for Flasher service.
// All implementations must embed UnimplementedFlasherServer
// for forward compatibility.
//
// Provides RPCs to flash Arduino images onto selected boards.
type FlasherServer interface {
	// Retrieves the images available for flashing
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Starts the flashing process
	Flash(*FlashRequest, grpc.ServerStreamingServer[FlashResponse]) error
	// Returns the available space for a given filesystem path
	// located on the arduino-flasher-cli storage device.
	GetAvailableFreeSpace(context.Context, *GetAvailableFreeSpaceRequest) (*GetAvailableFreeSpaceResponse, error)
	mustEmbedUnimplementedFlasherServer()
}

// UnimplementedFlasherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlasherServer struct{}

func (UnimplementedFlasherServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedFlasherServer) Flash(*FlashRequest, grpc.ServerStreamingServer[FlashResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Flash not implemented")
}
func (UnimplementedFlasherServer) GetAvailableFreeSpace(context.Context, *GetAvailableFreeSpaceRequest) (*GetAvailableFreeSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableFreeSpace not implemented")
}
func (UnimplementedFlasherServer) mustEmbedUnimplementedFlasherServer() {}
func (UnimplementedFlasherServer) testEmbeddedByValue()                 {}

// UnsafeFlasherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlasherServer will
// result in compilation errors.
type UnsafeFlasherServer interface {
	mustEmbedUnimplementedFlasherServer()
}

func RegisterFlasherServer(s grpc.ServiceRegistrar, srv FlasherServer) {
	// If the following call pancis, it indicates UnimplementedFlasherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flasher_ServiceDesc, srv)
}

func _Flasher_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlasherServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flasher_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlasherServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flasher_Flash_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FlashRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlasherServer).Flash(m, &grpc.GenericServerStream[FlashRequest, FlashResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Flasher_FlashServer = grpc.ServerStreamingServer[FlashResponse]

func _Flasher_GetAvailableFreeSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableFreeSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlasherServer).GetAvailableFreeSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flasher_GetAvailableFreeSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlasherServer).GetAvailableFreeSpace(ctx, req.(*GetAvailableFreeSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Flasher_ServiceDesc is the grpc.ServiceDesc for Flasher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flasher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cc.arduino.flasher.v1.Flasher",
	HandlerType: (*FlasherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Flasher_List_Handler,
		},
		{
			MethodName: "GetAvailableFreeSpace",
			Handler:    _Flasher_GetAvailableFreeSpace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Flash",
			Handler:       _Flasher_Flash_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cc/arduino/flasher/v1/commands.proto",
}
