name: Run Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.25.1"

jobs:
  go-test-orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run `orchestrator` tests
        run: task test:orchestrator

  go-test-pkg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: install dependencies [Linux]
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run `pkg` tests
        run: task test:pkg
